project:
  type: website
  output-dir: docs

execute:
  freeze: auto    # congela salidas: no re-ejecuta salvo que cambie el código

website:
  title: "Machine Learning — Proyecto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Clasificación
        menu:
          - href: clasificacion_incidentes.qmd
            text: Incidentes (clásico)
          - href: tweets_classification.qmd
            text: Tweets Classification
          - href: regresion_pm25.qmd
            text: Regresión
      - href: examen_ml.qmd         # ← NUEVO
        text: Examen (TOXICITY)
    
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    embed-resources: true
    fig-format: png


