project:
  type: website
  output-dir: docs

execute:
  freeze: auto    # congela salidas: no re-ejecuta salvo que cambie el código

website:
  title: "Examen Final — ML con Tweets (TOXICITY)"
  description: "Análisis, tweets con métricas de toxicidad."
  site-url: "https://nsanchez1418.github.io/examen-ml-toxicity-2025/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Clasificación
        menu:
          - href: clasificacion_incidentes.qmd
            text: Incidentes (clásico)
          - href: tweets_classification.qmd
            text: Tweets Classification
          - href: regresion_pm25.qmd
            text: Regresión
      - href: examen_ml.qmd         # ← NUEVO
        text: Examen (TOXICITY)
  page-footer:
    left: "Noé Sánchez"  
    right: "Repositorio en [GitHub](https://github.com/NSanchez1418/examen-ml-toxicity-2025)"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    embed-resources: true
    fig-format: png


