project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning — Proyecto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Clasificación
        menu:
          - href: clasificacion_incidentes.qmd
            text: Incidentes (clásico)
          - href: tweets_classification.qmd
            text: Tweets Classification
      - href: regresion_pm25.qmd
        text: Regresión

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    embed-resources: true


